# Generated by Django 2.1.11 on 2020-05-24 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('editoras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('data_publicacao', models.DateField(null=True)),
                ('autor', models.CharField(blank=True, max_length=30)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=5)),
                ('paginas', models.IntegerField(blank=True, null=True)),
                ('tipo_livro', models.PositiveSmallIntegerField(choices=[(1, 'Capa Dura'), (2, 'Livro de Bolso'), (3, 'E-book'), (4, 'E-Pub')])),
                ('isbn', models.CharField(max_length=15)),
                ('data_lancamento', models.DateField(auto_now_add=True)),
                ('editora', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='editoras.Editora')),
            ],
            options={
                'verbose_name': 'Livro',
                'verbose_name_plural': 'Livros',
                'db_table': 'Livro',
                'ordering': ['titulo'],
                'managed': True,
            },
        ),
    ]
